export enum PermissionModule {
  USERS = 'users',
  ROLES = 'roles',
  TENANTS = 'tenants',
  FACTORIES = 'factories',
  INVENTORY = 'inventory',
  WAREHOUSES = 'warehouses',
  SUPPLIERS = 'suppliers',
  PURCHASE_ORDERS = 'purchase_orders',
  PRODUCTION = 'production',
  PRODUCTION_WORKFLOW = 'production_workflow',
  COSTING = 'costing',
  EMPLOYEES = 'employees',
  ATTENDANCE = 'attendance',
  QUALITY_CONTROL = 'quality_control',
  FINISHED_GOODS = 'finished_goods',
  DASHBOARDS = 'dashboards',
  REPORTING = 'reporting',
  POS_INTEGRATION = 'pos_integration',
  SUBSCRIPTIONS = 'subscriptions',
  FEATURE_FLAGS = 'feature_flags',
  BILLING = 'billing',
  FILE_MANAGEMENT = 'file_management',
  AUDIT_LOGS = 'audit_logs',
  NOTIFICATIONS = 'notifications',
  SYSTEM_SETTINGS = 'system_settings',
}

export enum PermissionAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  APPROVE = 'approve',
  REJECT = 'reject',
  EXPORT = 'export',
  IMPORT = 'import',
  VIEW_SENSITIVE = 'view_sensitive',
  MANAGE = 'manage',
}
