export const APP_NAME = 'SHAA Apparel ERP';

export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PRODUCT_TRACKER: '/product-tracker',
  DESIGN_MODULE: '/design-module',
  PATTERN_MAKING: '/pattern-making',
  SAMPLE_MAKING: '/sample-making',
  CUTTING_DEPT: '/cutting-dept',
  SEWING_DEPT: '/sewing-dept',
  QUALITY_CONTROL: '/quality-control',
  FINISHED_GOODS: '/finished-goods',
  WAREHOUSE: '/warehouse',
  RECIPE_MANAGEMENT: '/recipe-management',
  PURCHASING: '/purchasing',
  SUPPLIERS: '/suppliers',
  COST_CALCULATION: '/cost-calculation',
  POS_SALES: '/pos-sales',
  PHOTO_DISTRIBUTION: '/photo-distribution',
  ATTENDANCE: '/attendance',
  KPI_INCENTIVES: '/kpi-incentives',
  REPORTS: '/reports',
  AUDIT_LOG: '/audit-log',
  USER_ROLES: '/user-roles',
  // legacy kept for compat
  PRODUCTION: '/production',
  INVENTORY: '/inventory',
  WAREHOUSES: '/warehouse',
  PURCHASE_ORDERS: '/purchasing',
  COSTING: '/cost-calculation',
  REPORTING: '/reports',
  USERS: '/user-roles',
  ROLES: '/user-roles',
  SETTINGS: '/user-roles',
  PROFILE: '/user-roles',
  POS_INTEGRATION: '/pos-sales',
} as const;

export const PERMISSIONS = {
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  ROLES_READ: 'roles:read',
  ROLES_CREATE: 'roles:create',
  ROLES_UPDATE: 'roles:update',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_UPDATE: 'inventory:update',
  PRODUCTION_READ: 'production:read',
  PRODUCTION_CREATE: 'production:create',
  COSTING_VIEW_SENSITIVE: 'costing:view_sensitive',
  REPORTING_EXPORT: 'reporting:export',
} as const;

export const STATUS_LABELS: Record<string, string> = {
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  SUSPENDED: 'Suspended',
  PENDING_VERIFICATION: 'Pending',
  DRAFT: 'Draft',
  PLANNED: 'Planned',
  IN_PROGRESS: 'In Progress',
  PARTIALLY_COMPLETED: 'Partial',
  COMPLETED: 'Completed',
  ON_HOLD: 'On Hold',
  CANCELLED: 'Cancelled',
  SUBMITTED: 'Submitted',
  APPROVED: 'Approved',
  PARTIALLY_RECEIVED: 'Partial',
  FULLY_RECEIVED: 'Received',
  TRIAL: 'Trial',
  PAST_DUE: 'Past Due',
  EXPIRED: 'Expired',
};

export const STATUS_COLORS: Record<string, string> = {
  ACTIVE: 'badge-green',
  COMPLETED: 'badge-green',
  FULLY_RECEIVED: 'badge-green',
  APPROVED: 'badge-green',
  INACTIVE: 'badge-gray',
  DRAFT: 'badge-gray',
  CANCELLED: 'badge-gray',
  SUSPENDED: 'badge-red',
  PAST_DUE: 'badge-red',
  EXPIRED: 'badge-red',
  IN_PROGRESS: 'badge-blue',
  PLANNED: 'badge-blue',
  SUBMITTED: 'badge-blue',
  ON_HOLD: 'badge-yellow',
  TRIAL: 'badge-yellow',
  PARTIALLY_COMPLETED: 'badge-yellow',
  PARTIALLY_RECEIVED: 'badge-yellow',
  PENDING_VERIFICATION: 'badge-yellow',
};

export const PAGINATION_DEFAULT = {
  PAGE: 1,
  LIMIT: 20,
  LIMITS: [10, 20, 50, 100],
} as const;
